# Your information
name:    Craig Wickesser
tagline: 
twitter: mind_scratch
github:  mindscratch
email:   craig@mindscratch.org

# Google Analytics
ga_id:  UA-19519852-1 

# Admin credentials
login:    <%= ENV["obtvse_login"] ? ENV["obtvse_login"] : "username" %>
password: <%= ENV["obtvse_password"] ? ENV["obtvse_password"] : "password" %>

# Amazon S3
s3_in_development: true
access_key_id:     <%= ENV["access_key_id"] ? ENV["access_key_id"] : "" %>
secret_access_key: <%= ENV["secret_access_key"] ? ENV["secret_access_key"] : "" %>
bucket:            bucket_name

#0HJCHEM8VR464K2Y86G2
#oRQkWSrw8XhY2slQft9GHFVEzmwVu480hm2EvVF/

